version: '3.4'

services:
  temperature.api:
    container_name: temperature.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  angularapp:
    container_name: angularapp
    ports:
      - "4200:4200"
    volumes:
      - ./webapps/AngularApp/ClientApp:/app
